categories:
- Tool Dependency Packages
- Proteomics
description: A ruby gem with many proteomics tools
long_description: |
  Protk is a suite of tools for proteomics. It aims to present a simple and
  consistent command-line interface across otherwise disparate third party
  tools. The following analysis tasks are currently supported;

  * Tandem MS search with X!Tandem, Mascot, OMSSA and MS-GF+
  * Peptide and Protein inference with Peptide Prophet, iProphet and Protein Prophet
  * Conversion of pepXML or protXML to tabulular format
  * Proteogenomics (mapping peptides to genomic coordinates)

  https://github.com/iracooke/protk
name: package_protk_1_4_1
owner: iracooke
remote_repository_url: https://github.com/iracooke/protk-galaxytools/tree/master/packages/package_protk_1_4_1
type: tool_dependency_definition
