categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads omssa version 2.1.9
long_description: OMSSA is a search engine for matching Tandem MS spectra to peptides. It is no longer maintained but remains useful. 
name: package_omssa_2_1_9
owner: iracooke
remote_repository_url: https://github.com/iracooke/protk-galaxytools/tree/master/packages/package_omssa_2_1_9
type: tool_dependency_definition