categories: [Proteomics]
description: MSGF+ MS MS Search
homepage_url: https://github.com/iracooke/protk-galaxytools
long_description: Search MSMS Spectra against a protein database with MS-GF+
name: msgfplus
owner: iracooke
remote_repository_url: https://github.com/iracooke/protk-galaxytools/blob/master/msgfplus/.shed.yml
