categories:
- Tool Dependency Packages
description: Downloads and compiles the Gnome XML libraries.
long_description: |
  Libxml2 is the XML C parser and toolkit developed for the Gnome project (but usable outside of the Gnome platform), it is free software available under the MIT License. XML itself is a metalanguage to design markup languages, i.e. text language where semantic and structure are added to the content using extra "markup" information enclosed between angle brackets. HTML is the most well-known markup language. Though the library is written in C a variety of language bindings make it available in other environments.
name: package_libxml2_2_9_1
owner: iracooke
remote_repository_url: https://github.com/iracooke/protk-galaxytools/tree/master/packages/package_libxml2_2_1_9
type: tool_dependency_definition
